"use client";
import * as THREE from 'three'
import { useThree } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { Physics, RigidBody, CuboidCollider } from "@react-three/rapier";
import { useRef, useEffect } from 'react'

export default function Model() {
    const { viewport, camera } = useThree()  
    const ref = useRef()

    useEffect(() => {
        const vec = new THREE.Vector3()
        function handleScroll(e) {
            vec.lerp({ x: 0, y: - (window.scrollY * 0.01), z: 0 }, 1)
            ref.current?.setNextKinematicTranslation(vec)
            camera.position.y = -(window.scrollY * 0.01)
        }
        window.addEventListener('scroll', handleScroll)
        return () => window.removeEventListener('scroll', handleScroll)
    }, []);

    return (

        <Physics gravity={[0, -10, 0]} >
            <Foods scale={2} />
                <RigidBody ref={ref} type='kinematicPosition'>
                    <CuboidCollider name='bottom' position={[0, -4, 0]} args={[20, 0.5, 4]}/>
                    <CuboidCollider name='top' position={[0, 8, 0]} args={[20, 0.5, 4]} />
                    <CuboidCollider name='back' position={[0, 0, -1]} args={[20, 20, 0.5]} />
                    <CuboidCollider name='front' position={[0, 0, 1.2]} args={[20, 20, 0.5]} />
                    <CuboidCollider name='right' position={[viewport.width / 2 + 1, 0, 0]} args={[0.5, 20, 4]} />
                    <CuboidCollider name='left' position={[-viewport.width / 2 - 1, 0, 0]} args={[0.5, 20, 4]} />
                </RigidBody>
        </Physics>

    )
}

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
function Foods(props) {
    const { nodes, materials } = useGLTF("/foods.glb");
    return (
        <group {...props} dispose={null} rotation={[Math.PI/2, 0, 0]}>
            <RigidBody colliders='hull'>
                <group position={[1.126, 0, -0.75]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.apple_1.geometry}
                        material={materials.red}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.apple_1_1.geometry}
                        material={materials.brown}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.apple_1_2.geometry}
                        material={materials.green}
                    />
                </group>
            </RigidBody>
            <RigidBody colliders='hull'>
                <group position={[-0.01, 0, -0.886]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.banana_1.geometry}
                        material={materials["brownDark.003"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.banana_1_1.geometry}
                        material={materials.yellow}
                    />
                </group>
            </RigidBody>
            <RigidBody colliders='hull'>
                <group position={[-0.477, 0, 0.53]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.cabbage_1.geometry}
                        material={materials["green.008"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.cabbage_1_1.geometry}
                        material={materials["_defaultMat.006"]}
                    />
                </group>
            </RigidBody>
            <RigidBody colliders='hull'>
                <group position={[-0.32, 0, -0.706]} rotation={[Math.PI / 2, 0, 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carrot_1.geometry}
                        material={materials["orange.001"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carrot_1_1.geometry}
                        material={materials["green.011"]}
                    />
                </group>
            </RigidBody>
            <RigidBody colliders='hull'>
                <group position={[-1.105, 0, 0.298]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carton_1.geometry}
                        material={materials["purple.003"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carton_1_1.geometry}
                        material={materials["_defaultMat.009"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.carton_1_2.geometry}
                        material={materials["white.002"]}
                    />
                </group>
            </RigidBody>
            <RigidBody colliders='hull'>
                <group position={[0.159, 0, -0.13]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.corn_1.geometry}
                        material={materials["green.016"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.corn_1_1.geometry}
                        material={materials["yellow.009"]}
                    />
                </group>
            </RigidBody>
            <RigidBody colliders='hull'>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.croissant.geometry}
                    material={materials["brown.015"]}
                    position={[0.621, 0, -0.012]}
                />
            </RigidBody>
            <RigidBody colliders='hull'>
                <group position={[-0.008, 0, 0.842]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.eggplant_1.geometry}
                        material={materials["purple.005"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.eggplant_1_1.geometry}
                        material={materials["green.020"]}
                    />
                </group>
            </RigidBody>
            <RigidBody colliders='hull'>
                <group position={[0.6, 0, 0.804]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.fish_1.geometry}
                        material={materials["pink.001"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.fish_1_1.geometry}
                        material={materials["greyLight.009"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.fish_1_2.geometry}
                        material={materials["_defaultMat.022"]}
                    />
                </group>
            </RigidBody>
            <RigidBody colliders='hull'>
                <group position={[-1.22, 0, -0.052]} rotation={[Math.PI / 2, 0 , 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.leek_1.geometry}
                        material={materials["green.022"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.leek_1_1.geometry}
                        material={materials["_defaultMat.026"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.leek_1_2.geometry}
                        material={materials["greenDark.001"]}
                    />
                </group>
            </RigidBody>
            <RigidBody colliders='hull'>
                <group position={[-1.179, 0, 0.999]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.loafRound_1.geometry}
                        material={materials["brownDark.026"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.loafRound_1_1.geometry}
                        material={materials["brown.025"]}
                    />
                </group>
            </RigidBody>
            <RigidBody colliders='hull'>
                <group position={[-1.029, 0, -0.604]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.meatRaw_1.geometry}
                        material={materials["white.013"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.meatRaw_1_1.geometry}
                        material={materials["pink.002"]}
                    />
                </group>
            </RigidBody>
            <RigidBody colliders='hull'>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.onion.geometry}
                    material={materials["brown.029"]}
                    position={[1.045, 0, -0.359]}
                />
            </RigidBody>
            <RigidBody colliders='hull'>
                <group position={[1.173, 0, 0.316]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.orange_1.geometry}
                        material={materials["orange.003"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.orange_1_1.geometry}
                        material={materials["green.023"]}
                    />
                </group>
            </RigidBody>
            <RigidBody colliders='hull'>
                <group position={[1.121, 0, 0.623]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.pear_1.geometry}
                        material={materials["green.025"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.pear_1_1.geometry}
                        material={materials["brown.033"]}
                    />
                </group>
            </RigidBody>
            <RigidBody colliders='hull'>
                <group position={[-0.3, 0, -0.138]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.pumpkin_1.geometry}
                        material={materials["green.030"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.pumpkin_1_1.geometry}
                        material={materials["orange.005"]}
                    />
                </group>
            </RigidBody>
        </group>
    );
}

useGLTF.preload("/foods.glb");
